apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: cnbrchaos
    app.kubernetes.io/version: ci
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: cnbrchaos
    app.kubernetes.io/managed-by: kubectl
    name: cnbrchaos
  name: cnbrchaos
  namespace: cnbr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cnbrchaos
        app.kubernetes.io/version: ci
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: cnbr
        app.kubernetes.io/managed-by: kubectl
        name: chaos-operator
    spec:
      serviceAccountName: cnbrchaos
      containers:
        - name: chaos-operator
          image: cnbrchaos/chaos-operator:ci
          command:
          - chaos-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: CHAOS_RUNNER_IMAGE
              value: "cnbrchaos/chaos-runner:ci"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "chaos-operator"
